// <auto-generated />
namespace realestateinspectorService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addedproeprtytypeentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedproeprtytypeentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201502260615263_Added proeprty type entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
