//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Blend.SampleData.SecondPageDataSource
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SecondPageDataSource { }
#else

	public class SecondPageDataSource : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public SecondPageDataSource()
		{
			try
			{
				Uri resourceUri = new Uri("ms-appx:/SampleData/SecondPageDataSource/SecondPageDataSource.xaml", UriKind.RelativeOrAbsolute);
				Windows.UI.Xaml.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private CurrentProperty _CurrentProperty = new CurrentProperty();

		public CurrentProperty CurrentProperty
		{
			get
			{
				return this._CurrentProperty;
			}

			set
			{
				if (this._CurrentProperty != value)
				{
					this._CurrentProperty = value;
					this.OnPropertyChanged("CurrentProperty");
				}
			}
		}
	}

	public class CurrentProperty : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
#endif
}
